version: "3.8"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend
        
    backend:
        image: my-backend-image
        environment:
            DB_URL: jdbc:postgresql://postgres:5432/mydb
            DB_USER: myuser
            DB_PASS: mypassword
        networks:
            - backend
        depends_on:
            - postgres
        ports:
            - "8081:8081"
    webserver:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        networks:
            - backend
volumes:
    pgdata:
networks:
    backend:
